const api = {
  login: "/login/",
  logout: "/logout/",
  me: "/profile/",
  finacle: "/finacle/",
  report: "/report",
  permission: "/permissions/",
  changepassword: "",
  ssoLogin: "/login/",
  ssoRegister: "/third-party/register/",
  darta: "/darta/",
  chalani: "/chalani/",
  registration: "/employee_create_data/",
  driver: "/drivers/",
  driverShift: "/vehicle-reservation/bulk-driver-shift-api",
  shift: "/driver-shift/",
  vehicle: "/vehicle/",
  unassignedVehicle: "/api/v1/unassigned-vehicles/",
  reservation: "/api/v1/reservation/",
  reservationStatistics: "/api/v1/statistics/",
  reserved: "/api/v1/reservation/",
  recommended: "/api/v1/reservation/",
  confirmed: "/api/v1/reservation/",
  completed: "/api/v1/reservation/",
  track: "/api/v1/track-reservation/",
  courier: "/api/v1/courier/",
  branch: "/api/v1/branch/",
  department: "/api/v1/department/",
  appBuilder: "/api/v1/form-builder/forms/",
  appResponse: "/api/v1/form-builder/responses/",
  employee: "/api/v1/employee/",
  userEmail: "/api/v1/user-emails/",
  minEmployee: "/api/v1/user-emails/",
  user: "/api/v1/auth/user/",
  userPermission: "/api/v1/user/edit-permission/",
  staff: "/api/v1/user-emails/",
  // staff: '/api/v1/user/',
  group: "/api/v1/auth/group/",
  downloadDriverForm: "/api/v1/vehicle-reservation/download-csv-driver-form",
  downloadVehicleForm: "/api/v1/vehicle-reservation/download-csv-vehicle-form",
  downloadReservationForm: "/api/v1/vehicle-reservation/download-csv-reservation-form",
  uploadForm: "/api/v1/myfile/",
  maintanence: "/api/v1/maintenance-log/",
  exportCSV: {
    formResponse: "/api/v1/form-response-csv/",
    courier: "api/v1/courier-csv/",
    darta: "/api/v1/darta-csv/",
    chalani: "/api/v1/chalani-csv/",
    report: "/api/v1/get-report/",
  },
};

export default api;
