export const api = {
  me: "/api/v1/profile/",
  finacle: "api/finacle/",
  report: "api/report",
  permission: "/api/v1/auth/permissions/",
  changepassword: "",
  ssoLogin: "/api/v1/login/",
  ssoRegister: "/api/v1/third-party/register/",
  darta: "/api/v1/darta/",
  chalani: "/api/v1/chalani/",
  registration: "/api/v1/employee_create_data/",
  driver: "/api/v1/drivers/",
  driverShift: "/api/v1/vehicle-reservation/bulk-driver-shift-api",
  shift: "/api/v1/driver-shift/",
  vehicle: "/api/v1/vehicle/",
  unassignedVehicle: "/api/v1/unassigned-vehicles/",
  reservation: "/api/v1/reservation/",
  reservationStatistics: "/api/v1/statistics/",
  reserved: "/api/v1/reservation/",
  recommended: "/api/v1/reservation/",
  confirmed: "/api/v1/reservation/",
  completed: "/api/v1/reservation/",
  track: "/api/v1/track-reservation/",
  courier: "/api/v1/courier/",
  branch: "/api/v1/branch/",
  department: "/api/v1/department/",
  appBuilder: "/api/v1/form-builder/forms/",
  appResponse: "/api/v1/form-builder/responses/",
  employee: "/api/v1/employee/",
  userEmail: "/api/v1/user-emails/",
  minEmployee: "/api/v1/user-emails/",
  user: "/api/v1/auth/user/",
  userPermission: "/api/v1/user/edit-permission/",
  staff: "/api/v1/user-emails/",
  // staff: '/api/v1/user/',
  group: "/api/v1/auth/group/",
  downloadDriverForm: "/api/v1/vehicle-reservation/download-csv-driver-form",
  downloadVehicleForm: "/api/v1/vehicle-reservation/download-csv-vehicle-form",
  downloadReservationForm: "/api/v1/vehicle-reservation/download-csv-reservation-form",
  uploadForm: "/api/v1/myfile/",
  maintanence: "/api/v1/maintenance-log/",
  exportCSV: {
    formResponse: "/api/v1/form-response-csv/",
    courier: "api/v1/courier-csv/",
    darta: "/api/v1/darta-csv/",
    chalani: "/api/v1/chalani-csv/",
    report: "/api/v1/get-report/",
  },
  logout: "/api/v1/auth/token/logout/",
};

const appRoot = {
  driver: "/vehicle-reservation",
  courier: "/courier",
  appBuilder: "/digital-logbook-form",
  dartaChalani: "/darta-chalani",
  darta: "/darta",
  chalani: "/chalani",
  role: "/role",
  group: "/group",
  user: "/user",
};

export const app = {
  me: "/",
  changepassword: "/change-password",

  driver: {
    root: appRoot.driver,
    create: () => `${appRoot.driver}/create`,
    update: (id) => `${appRoot.driver}/update/${id}`,
    view: (id) => `${appRoot.driver}/view/${id}`,
    manage: (id) => `${appRoot.driver}/manage/${id}`,
    book: `${appRoot.driver}/reserve`,
    reservations: `${appRoot.driver}/reservations`,
    reserved: `${appRoot.driver}/reserved`,
    recommended: `${appRoot.driver}/recommended`,
    confirmed: `${appRoot.driver}/confirmed`,
    track: `${appRoot.driver}/track`,
    report: `${appRoot.driver}/report`,
    vehicle: `${appRoot.driver}/vehicle`,
    driver: `${appRoot.driver}/driver`,
    shift: `${appRoot.driver}/shift`,
    createShift: () => `${appRoot.driver}/shift/create`,
    updateShift: (id) => `${appRoot.driver}/shift/update/${id}`,

    createVehicle: () => `${appRoot.driver}/vehicle/create`,
    changeShift: `${appRoot.driver}/shift/change`,
    maintanence: `${appRoot.driver}/maintanence`,
  },

  courier: {
    root: appRoot.courier,
    create: () => `${appRoot.courier}/create`,
    update: (id) => `${appRoot.courier}/update/${id}`,
    view: (id) => `${appRoot.courier}/view/${id}`,
    manage: (id) => `${appRoot.courier}/manage/${id}`,
  },

  dartaChalani: {
    root: appRoot.dartaChalani,
  },

  darta: {
    root: appRoot.darta,
    create: () => `${appRoot.darta}/create`,
    update: (id) => `${appRoot.darta}/update/${id}`,
    view: (id) => `${appRoot.darta}/view/${id}`,
    manage: () => `${appRoot.darta}/manage/`,
  },
  chalani: {
    root: appRoot.chalani,
    create: () => `${appRoot.chalani}/create`,
    update: (id) => `${appRoot.chalani}/update/${id}`,
    view: (id) => `${appRoot.chalani}/view/${id}`,
    manage: () => `${appRoot.chalani}/manage`,
  },

  appBuilder: {
    root: appRoot.appBuilder,
    create: () => `${appRoot.appBuilder}/create`,
    update: (id) => `${appRoot.appBuilder}/update/${id}`,
    view: (id) => `${appRoot.appBuilder}/view/${id}`,
    manage: () => `${appRoot.appBuilder}/manage`,
  },
  user: {
    root: appRoot.user,
    create: () => `${appRoot.user}/create`,
    update: (id) => `${appRoot.user}/update/${id}`,
    view: (id) => `${appRoot.user}/view/${id}`,
    manage: () => `${appRoot.user}/manage/`,
  },
  group: {
    root: appRoot.group,
    create: () => `${appRoot.group}/create`,
    update: (id) => `${appRoot.group}/update/${id}`,
    view: (id) => `${appRoot.group}/view/${id}`,
    manage: () => `${appRoot.group}/manage/`,
  },
  role: {
    root: appRoot.role,
    create: () => `${appRoot.role}/create`,
    update: (id) => `${appRoot.role}/update/${id}`,
    view: (id) => `${appRoot.role}/view/${id}`,
    manage: () => `${appRoot.role}/manage/`,
    execute: (id) => `${appRoot.role}/execute/${id}`,
  },
};
