export const SET_IS_LOADING = '@@annotationImage/SET_IS_LOADING';

export const SET_IS_SUBMITTING = '@@annotationImage/SET_IS_SUBMITTING';

export const SET_ANNOTATION_IMAGE_DATA =
  '@@annotationImage/SET_ANNOTATION_IMAGE_DATA';
export const SET_ANNOTATION_IMAGES_DATA =
  '@@annotationImage/SET_ANNOTATION_IMAGES_DATA';

export const SET_ANNOTATION_IMAGES_METADATA =
  '@@annotationImage/SET_ANNOTATION_IMAGES_METADATA';

export const SET_SEARCHED_ANNOTATION_IMAGES_DATA =
  '@@annotationImage/SET_SEARCHED_ANNOTATION_IMAGES_DATA';
export const RESET_SEARCHED_ANNOTATION_IMAGES_DATA =
  '@@annotationImage/RESET_SEARCHED_ANNOTATION_IMAGES_DATA';

export const CREATE_ANNOTATION_IMAGE_DATA =
  '@@annotationImage/CREATE_ANNOTATION_IMAGE_DATA';

export const REMOVE_ANNOTATION_IMAGE_DATA =
  '@@annotationImage/REMOVE_ANNOTATION_IMAGE_DATA';

export const UPDATE_ANNOTATION_IMAGE_DATA =
  '@@annotationImage/UPDATE_ANNOTATION_IMAGE_DATA';
