export const SET_IS_LOADING = "@@liveclient/SET_IS_LOADING";

export const SET_IS_SUBMITTING = "@@liveclient/SET_IS_SUBMITTING";

export const SET_LIVECLIENT_DATA = "@@liveclient/SET_LIVECLIENT_DATA";
export const SET_LIVECLIENTS_DATA = "@@liveclient/SET_LIVECLIENTS_DATA";

export const SET_LIVECLIENTS_METADATA = "@@liveclient/SET_LIVECLIENTS_METADATA";

export const SET_SEARCHED_LIVECLIENTS_DATA = "@@liveclient/SET_SEARCHED_LIVECLIENTS_DATA";
export const RESET_SEARCHED_LIVECLIENTS_DATA = "@@liveclient/RESET_SEARCHED_LIVECLIENTS_DATA";

export const CREATE_LIVECLIENT_DATA = "@@liveclient/CREATE_LIVECLIENT_DATA";

export const REMOVE_LIVECLIENT_DATA = "@@liveclient/REMOVE_LIVECLIENT_DATA";

export const UPDATE_LIVECLIENT_DATA = "@@liveclient/UPDATE_LIVECLIENT_DATA";

export const SET_FCRS_LIVECLIENT_QUERY_RESULT_DATA =
  "@@liveclient/SET_FCRS_LIVECLIENT_QUERY_RESULT_DATA";
