const res = {
  items: [
    {
      customer_type: 'organization',
      organization_name: 'Sandip',
      organizations_email: ['sandip@mail.com'],
      credit_limit: '500000.0',
      balance_amount: '100000.0',
      operations_email: ['123@mail.com'],
      invoice_email: ['234@mail.com'],
      phone_numbers: ['886/23124124123213'],
      website: 'https://sadnip.com',
      business_since: '2023-03-01',
      business_invoice_type: '1',
      country: 1,
      currency: 2,
      tax_percentage: 0,
      tax_type: 'Corporate',
      documents: [],
      notes: '',
      id: 4,
      credit_limit_currency: 'Yen',
      balance_amount_currency: 'Yen',
      status: false,
      customer_address: [
        {
          id: 4,
          customer_id: 4,
          address_type: 'Primary',
          address_line: 'Budalinkantha',
          location: null,
          city: 'Abha',
          state: 'Asir',
          territory: 1,
          country: 1,
          zip_code: '223',
        },
      ],
    },
    {
      customer_type: 'organization',
      organization_name: 'refrefre',
      organizations_email: ['yogeshorganization@gmail.com'],
      credit_limit: '123.0',
      balance_amount: '21.0',
      operations_email: ['operator@gmail.com'],
      invoice_email: ['invoice@gmail.com'],
      phone_numbers: ['886/124356453'],
      website: '',
      business_since: null,
      business_invoice_type: '1',
      country: 1,
      currency: 2,
      tax_percentage: 0,
      tax_type: 'Corporate',
      documents: [],
      notes: 'refrefre',
      id: 8,
      credit_limit_currency: 'Yen',
      balance_amount_currency: 'Yen',
      status: true,
      customer_address: [
        {
          id: 9,
          customer_id: 8,
          address_type: 'Secondary',
          address_line: 'fre',
          location: null,
          city: 'ushaed',
          state: 'mni',
          territory: 3,
          country: 2,
          zip_code: 'ferfe',
        },
      ],
    },
  ],
  total: 2,
  page: 1,
  size: 5,
  pages: 1,
  headers: {
    id: 'Id',
    customer_type: 'Customer Type',
    organization_name: 'Organization Name',
    // organizations_email: 'Organizations Email',
    invoice_email: 'Invoice Email',
    website: 'Website',
    status: 'Status',
    // updated_at: 'Last Modified at',
    // updated_by: 'Last Modified by',
    // created_at: 'Created at',
    // created_by: 'Created By',
  },
  info: {},
};

export default res;
